---
- name: "Install an all-in-one wordpress instance - deploy_wordpress_role.yml"
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    wp_version: 5.0.3
    wp_mysql_db: 'database_name_here'
    wp_mysql_user: 'username_here'
    wp_mysql_password: "{{ lookup('ansible.builtin.password', '/root/db_wp_user', chars=['ascii_letters']) }}"
    wp_webserver: nginx
    wp_sitename: example.com
    wp_admin_email: 'admin@example.com'
    wp_install_dir: "/var/www/{{ wp_sitename }}"

  roles:
    - makarenalabs.wordpress