---
- name: "Install db-server"
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pip

- name: "Install bottle python package"
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - pymysql
    - mysql-connector-python
 
- name: "Start db-server"    
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: "Create a new database with name iac_wordpress"
  community.mysql.mysql_db:
    name: iac_wordpress
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: "Create wordpress user"
  community.mysql.mysql_user:
    name: "iac_wp"
    host: localhost
    password: "{{ lookup('ansible.builtin.password', '/tmp/iac_wordpress', chars=['ascii_letters']) }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    priv: 
      'iac_wordpress.*': 'SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
